# Generated by Django 5.2.7 on 2025-10-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_transaction_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Dining', 'Dining'), ('Fitness & Health', 'Fitness & Health'), ('Groceries', 'Groceries'), ('Shopping', 'Shopping'), ('Crypto', 'Crypto'), ('Utilities', 'Utilities'), ('Other', 'Other')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='category_source',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('user', 'User'), ('ai', 'AI'), ('rule', 'Rule'), ('import', 'Import')], default='unknown', max_length=16),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
