# Generated by Django 5.2.7 on 2025-10-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_transaction_ai_confidence_transaction_ai_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
