# Generated by Django 5.2.7 on 2025-10-21 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_transaction_deleted_at_transaction_deleted_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('bank', 'Bank account'), ('cash', 'Cash reserve'), ('savings', 'Savings account')], default='bank', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_sources', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='money_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.moneysource'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'is_deleted', 'date'], name='finance_tra_user_id_e7da4e_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'is_deleted', 'money_source', 'date'], name='finance_tra_user_id_81d955_idx'),
        ),
        migrations.AddIndex(
            model_name='moneysource',
            index=models.Index(fields=['user', 'is_active'], name='finance_mon_user_id_a8c592_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='moneysource',
            unique_together={('user', 'name')},
        ),
    ]
