# Generated by Django 5.2.7 on 2025-10-25 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_seed_moneysource_and_recompute_fingerprints'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneysource',
            name='balance_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moneysource',
            name='current_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
