# Generated by Django 5.2.7 on 2025-10-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_moneysource_balance_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneysource',
            name='manual_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='moneysource',
            name='manual_currency',
            field=models.CharField(default='EUR', max_length=8),
        ),
    ]
