# Generated by Django 5.2.7 on 2025-11-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_tx_goal_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='monthly_cap',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
