# Generated by Django 5.2.7 on 2025-11-13 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_advisorreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('prev_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('curr_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tx_delta_between', models.DecimalField(decimal_places=2, max_digits=14)),
                ('expected_curr', models.DecimalField(decimal_places=2, max_digits=14)),
                ('diff', models.DecimalField(decimal_places=2, max_digits=14)),
                ('note', models.CharField(blank=True, default='', max_length=240)),
                ('snapshot_curr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_prev', to='finance.balancesnapshot')),
                ('snapshot_prev', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_next', to='finance.balancesnapshot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['user', 'detected_at'], name='finance_bal_user_id_495f72_idx')],
            },
        ),
    ]
