# Generated by Django 5.2.7 on 2025-11-14 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_balanceanomaly'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(blank=True, choices=[('Income', 'Income'), ('Cash', 'Cash'), ('Dining', 'Dining'), ('Fitness & Health', 'Fitness & Health'), ('Groceries', 'Groceries'), ('Shopping', 'Shopping'), ('Crypto', 'Crypto'), ('Utilities', 'Utilities'), ('Other', 'Other'), ('Subscriptions', 'Subscriptions'), ('Transportation', 'Transportation')], max_length=32, null=True),
        ),
        migrations.CreateModel(
            name='OnboardingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories_done', models.BooleanField(default=False)),
                ('upload_done', models.BooleanField(default=False)),
                ('balance_done', models.BooleanField(default=False)),
                ('teach_ai_done', models.BooleanField(default=False)),
                ('ready_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_state', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
