# Generated by Django 5.2.7 on 2025-11-17 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_alter_transaction_category_onboardingstate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('autocategorize', 'Auto-categorize'), ('recheck', 'Recheck')], max_length=32)),
                ('mode', models.CharField(choices=[('uncat', 'Uncategorized only'), ('ai', 'AI-labeled'), ('all', 'All (excl. user)')], default='uncat', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('considered', models.PositiveIntegerField(default=0)),
                ('applied', models.PositiveIntegerField(default=0)),
                ('parked', models.PositiveIntegerField(default=0)),
                ('skipped', models.PositiveIntegerField(default=0)),
                ('log_text', models.TextField(blank=True, default='')),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_runs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AiRunItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('action', models.CharField(choices=[('applied', 'Applied'), ('parked', 'Parked'), ('skipped', 'Skipped')], max_length=16)),
                ('new_category_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.category')),
                ('old_category_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.category')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.airun')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_run_items', to='finance.transaction')),
            ],
        ),
        migrations.AddIndex(
            model_name='airun',
            index=models.Index(fields=['user', 'started_at'], name='finance_air_user_id_221ba2_idx'),
        ),
        migrations.AddIndex(
            model_name='airun',
            index=models.Index(fields=['user', 'status'], name='finance_air_user_id_72fd90_idx'),
        ),
        migrations.AddIndex(
            model_name='airun',
            index=models.Index(fields=['kind', 'status'], name='finance_air_kind_789d84_idx'),
        ),
        migrations.AddIndex(
            model_name='airunitem',
            index=models.Index(fields=['run'], name='finance_air_run_id_f54826_idx'),
        ),
        migrations.AddIndex(
            model_name='airunitem',
            index=models.Index(fields=['transaction'], name='finance_air_transac_8748a4_idx'),
        ),
    ]
