# Generated by Django 5.2.7 on 2025-11-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_airun_airunitem_airun_finance_air_user_id_221ba2_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airun',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
