# Generated by Django 5.2.7 on 2025-11-23 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_airun_notified_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('lookup_key', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('asset_type', models.CharField(choices=[('crypto', 'Crypto'), ('stock', 'Stock/ETF')], max_length=10)),
                ('current_price_eur', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('price_updated_at', models.DateTimeField(blank=True, null=True)),
                ('currency_raw', models.CharField(default='EUR', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='AssetHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.asset')),
                ('money_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='finance.moneysource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'asset', 'money_source')},
            },
        ),
    ]
