# Generated by Django 5.2.7 on 2025-11-25 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_asset_assetholding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetholding',
            name='money_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holdings', to='finance.moneysource'),
        ),
        migrations.AlterField(
            model_name='moneysource',
            name='type',
            field=models.CharField(choices=[('bank', 'Bank account'), ('cash', 'Cash reserve'), ('savings', 'Savings account'), ('investment', 'Investment')], default='bank', max_length=20),
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('crypto_total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('stock_total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='finance_por_user_id_467f03_idx')],
            },
        ),
    ]
