# Generated by Django 5.2.7 on 2025-12-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0023_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='exclude_investment_tax',
            field=models.BooleanField(default=False),
        ),
    ]
