# Generated by Django 5.2.7 on 2025-12-26 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0024_userprofile_exclude_investment_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_import_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.moneysource'),
        ),
    ]
