# Generated by Django 5.2.7 on 2026-01-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0025_userprofile_default_import_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(blank=True, choices=[('Income', 'Income'), ('Cash', 'Cash'), ('Dining', 'Dining'), ('Fitness & Health', 'Fitness & Health'), ('Groceries', 'Groceries'), ('Shopping', 'Shopping'), ('Crypto', 'Crypto'), ('Utilities', 'Utilities'), ('Other', 'Other'), ('Subscriptions', 'Subscriptions'), ('Transportation', 'Transportation'), ('Internal transfer', 'Internal transfer')], max_length=32, null=True),
        ),
    ]
