# Generated by Django 5.2.7 on 2026-03-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0028_feedbackticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account_delete_canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='account_delete_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='account_delete_scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
