# Generated by Django 5.2.7 on 2026-03-16 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0029_userprofile_account_delete_canceled_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingDataDeletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('transactions', 'Transactions')], default='transactions', max_length=32)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_data_deletions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['scope', 'scheduled_for'], name='finance_pen_scope_a88e0a_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'scope'), name='uniq_pending_data_deletion_user_scope')],
            },
        ),
    ]
