# Generated by Django 5.2.7 on 2026-04-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0031_subscriptiondecision'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_language',
            field=models.CharField(choices=[('lt', 'Lithuanian'), ('en', 'English')], default='lt', max_length=2),
        ),
    ]
