# Generated by Django 5.2.7 on 2026-04-19 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0032_userprofile_preferred_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeSourceDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_merchant', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('decision', models.CharField(choices=[('track', 'Track'), ('ignore', 'Ignore'), ('untrack', 'Untrack')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_source_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['normalized_merchant'],
                'indexes': [models.Index(fields=['user', 'decision'], name='finance_inc_user_id_d38c37_idx'), models.Index(fields=['user', 'normalized_merchant'], name='finance_inc_user_id_0e27ba_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'normalized_merchant'), name='uniq_income_source_decision_user_merchant')],
            },
        ),
    ]
