# Generated by Django 5.2.7 on 2026-04-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0033_incomesourcedecision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiondecision',
            name='decision',
            field=models.CharField(choices=[('track', 'Track'), ('ignore', 'Ignore'), ('untrack', 'Untrack')], max_length=16),
        ),
    ]
