# Generated by Django 5.2.7 on 2026-04-19 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0034_alter_subscriptiondecision_decision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundPairIgnore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tx_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_ignored_as_in', to='finance.transaction')),
                ('tx_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_ignored_as_out', to='finance.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ignored_refund_pairs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='finance_ref_user_id_c5566e_idx'), models.Index(fields=['user', 'created_at'], name='finance_ref_user_id_1cfa04_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'tx_out', 'tx_in'), name='uniq_refund_ignore_user_pair')],
            },
        ),
    ]
