# Generated by Django 5.2.7 on 2026-05-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0035_refundpairignore'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='beta_joined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_beta_tester',
            field=models.BooleanField(default=False),
        ),
    ]
